### ISSUE TITLE
Update wheelchair filter labels

### ISSUE THREAD

**Issue by mkfreeman** [mkfreeman/norc-map#26]
1 (some) 2 (none)

**Comment by mkfreeman** [comment]
@orcaomar do you think it makes sense to change this in the data, rather than in the UI? That might be more consistent / maintainable, rather than have some data-prep-ish step in the web app.

**Comment by orcaomar** [comment]
Yes agreed, we should have an intermediate cleaning step. I think that step should do as you say, but also it should do whatever they want with the shelter/bench/shelter w bench trio (which we'll discuss at the meeting).

Similarly, I didn't want to generate any more paths until we get their feedback on Thursday. For example, it's not clear to me if they also want the path to the trio mentioned above as well (like if we tick a "shelters" box, then we only show paths to shelters). Also, hopefully they've fiddled with the data a bit and can see themselves if they want me to tune the parameters on the path finding (or maybe they just want whatever Google Maps would give, because that will jive more with the lay user). 

Furthermore, we likely want to remove extraneous data from the file that we use on the webpage (there are a bunch of extra columns right now). They may actually not want such data publicly accessible, I don't know. 

Sorry, a lot to put in this bug. I can divide it all up into separate bugs which I can handle in one fell swoop after the Thursday meeting.

**Comment by mkfreeman** [comment]
Appreciate the thoughts! I'll open a data-cleaning issue with these bullet points in favor of this one. Closing in favor of #28.
