### ISSUE TITLE
Improved data preparation

### ISSUE THREAD

**Issue by mkfreeman** [mkfreeman/norc-map#28]
As came up in #26, we want to update the data prep process to: **edited**:
- [x] Remove extraneous columns
- [x] Update wheelchair filter labels: 1 (some) 2 (none)
- [x] "Deal with" the shelter/bench/shelter trio by using clearer names: Any shelter, Shelter with bench, Bench only
- [x] ~~To discuss: create additional paths to the closest TTC station with a given feature.~~ _not doing_

**Comment by mkfreeman** [comment]
Maybe also rename columns to the values we display in the table so we don't have to rename them? This will allow us to remove this code, though we'll have to go through and update references to the current columns. A little big of a pain to write `d.properties["Has shelter"]` instead of `d.properties.has_shelter`, but it's probably worth it to move more data-prep out of the web app. 

When doing this, you can go through and make the updates in the app (if you want more "practice" 😭 ), or feel free to just make a new .csv file, and then assign the issue to me and I'll make the updates. cc @orcaomar

**Comment by orcaomar** [comment]
Ok, I'm starting to do this now. This is what was agreed in the meeting:

UB: Uncovered Bench means ONLY BENCH (previously has_bench)
S_NO_SIT: Shelter but no inside bench means shelter to take cover but no where to sit (previous has_shelter)
S_WITH_SIT: Shelter with inside bench means shelter with a bench under it (previous has_shelter_with_bench)

BUT this doesn't seem to jive with the data. Reflections based on data below and more browsing is that the above is an incorrect interpretation. I'd say if S_NO_SIT and S_WITH_SIT are both true, what this means is that it has a shelter AND that shelter has a bench. 

When S_NO_SIT is true but S_WITH_SIT is false, that seems mostly correct (only 10 such in our dataset, a few are wrong but that looks like the shelter was recently removed. Still could be good to have ways for people to correct data).

With UB only true (so no shelter, just a bench) interestingly, at least from street view, while it's right they don't have shelters, many of these have no benches too! 

In the all false case, this seems, at quick glance, mostly right, though I've seen some old old shelters in those places. 



**Sanity Check**

First, the sanity check using Google Streetview using some locations. I give the Norc address, and then the boolean values of the variables described above from our original data describing the nearest stop:

1. GOOD: 22 Shallmar Blvd data says UB:false, S_NO_SIT:false, S_WITH_SIT:true  

2. GOOD: 125 Omni Dr data says UB:false, S_NO_SIT:false, S_WITH_SIT:false => it does have nothing

3. GOODISH: 835 Birchmount Road data says UB:false, S_NO_SIT:true, S_WITH_SIT:false => and this might be a good conclusion because while there does appear to be a bench here, it looks awful and non standard. [see here](https://www.google.com/maps/@43.7295137,-79.2778622,3a,15y,42.15h,86.9t/data=!3m6!1e1!3m4!1s5T9wbMd528vtLOFdPvza-w!2e0!7i16384!8i8192?entry=ttu) 

BAD

0. BAD: 1210 Don Mills data says UB:false, S_NO_SIT:true, S_WITH_SIT:false => but I only see a stop! [see here](https://www.google.com/maps/@43.7407531,-79.3447803,3a,75y,170.86h,86.29t/data=!3m6!1e1!3m4!1seyBbYTKc6rcsZF8Y-cjB8A!2e0!7i16384!8i8192?entry=ttu)

1. BAD: 44 Longbourne Dr data says UB:false, S_NO_SIT:true, S_WITH_SIT:true   => seems to actually have S_WITH_SIT and UB but no S_NO_SIT. [see here](https://www.google.com/maps/@43.6801601,-79.5687126,3a,75y,281.67h,78.53t/data=!3m6!1e1!3m4!1sV6a656-WC01hzDkeb9JI1A!2e0!7i16384!8i8192?entry=ttu)

2. BAD: 21 Maynard Ave data says UB:false, S_NO_SIT:false, S_WITH_SIT:false => seems to have a S_NO_SIT [see here](https://www.google.com/maps/@43.6367341,-79.4383231,3a,75y,324.51h,72.77t/data=!3m6!1e1!3m4!1sqnKTtbjBQWqH3k7HUfQ2sQ!2e0!7i16384!8i8192?entry=ttu)

3. BAD: 133 Wilton St data says UB:false, S_NO_SIT:true, S_WITH_SIT:true   => seems to actually have only S_WITH_SIT. [see here](https://www.google.com/maps/@43.6483399,-79.3704735,3a,75y,213.85h,70.87t/data=!3m6!1e1!3m4!1sbdGIS17ZGrJk_0bAsfvjZQ!2e0!7i16384!8i8192?entry=ttu)

4. BAD: 2715 Islington Ave data says UB:false, S_NO_SIT:true, S_WITH_SIT:true   => seems to actually have S_WITH_SIT and UB close by.. but not sure if the TTC would think of that bench as there's or the City's, so maybe just S_WITH_SIT. [see here](https://www.google.com/maps/@43.7411,-79.5669849,3a,75y,92.31h,72.29t/data=!3m6!1e1!3m4!1sxtRFP38cfWH47a5c9ZmFDQ!2e0!7i16384!8i8192?entry=ttu)

5. BAD: 1 Concorde Pl data says UB:false, S_NO_SIT:true, S_WITH_SIT:true   => seems to actually have UB true and S_WITH_SIT true. [see here](https://www.google.com/maps/@43.7281383,-79.3282995,3a,75y,62.27h,81.86t/data=!3m6!1e1!3m4!1shEpRxk-aoYdU9lNfv2cnDA!2e0!7i16384!8i8192?entry=ttu)

6. BAD: 3233 Eglinton Ave E data says UB:false, S_NO_SIT:true, S_WITH_SIT:false => seems to actually be the opposite, UB true, S_WITH_SIT:true. [see here](https://www.google.com/maps/@43.743849,-79.2121497,3a,75y,90t/data=!3m6!1e1!3m4!1sacuILtD7u2fRm8EjgEn_nA!2e0!7i16384!8i8192?entry=ttu)

7. BAD: 3680 Keele St data says UB:true, S_NO_SIT:true, S_WITH_SIT:false => seems to actually be S_WITH_SIT and UB. [see here](https://www.google.com/maps/@43.7547153,-79.4887155,3a,75y,59.78h,70.61t/data=!3m6!1e1!3m4!1sM0QvJ3gm7U7VcOwA98fkHg!2e0!7i16384!8i8192?entry=ttu)

8. BAD 4005 Bayview Ave says UB:false, S_NO_SIT:true, S_WITH_SIT:true => but only S_WITH_SIT seems true. [see here](https://www.google.com/maps/@43.8041148,-79.3925789,3a,75y,20.64h,88.68t/data=!3m6!1e1!3m4!1sE1_ZZsgQ9zKC0SEic1wKKQ!2e0!7i16384!8i8192?entry=ttu)

9. BADISH 110 Unity Road says UB:false, S_NO_SIT:true, S_WITH_SIT:false => it gets the shelter situation right, but there does also appear to be a bench! [see here](https://www.google.com/maps/@43.6781796,-79.3309757,3a,75y,248.53h,75.24t/data=!3m6!1e1!3m4!1sTUOb-FkcIN8i9kpDERfbJA!2e0!7i16384!8i8192?entry=ttu)

**Comment by orcaomar** [comment]
Ok, to go further, if they are all true, it seems to be 50% ish the time that they actually have a bench outside the shelter. Sometimes there is no bench outside the shelter. 

The number that don't have a shelter (based on variables) but do have a bench seems so small, but also a bit inaccurate. I think I need to combine variables, and the human readable version of all this will be:

HAS A SHELTER WITH A BENCH = has_shelter_with_bench = true

HAS A SHELTER WITHOUT A BENCH = has_shelter_with_bench = false but has_shelter = true

HAS ONLY A BENCH = has_bench but the other two are false

I don't think we can definitively make any comments about shelters that have benches and have outdoor benches. I will make these data on the backend. But let's do a quick call first.

**Comment by orcaomar** [comment]
@mkfreeman I could make this a property called "Amenity" and it has a few elements:

"Shelter With Bench Underneath, Shelter With No Seating, Bench Only"

and an empty Amenity property would mean it just has the stop post, nothing else. 

These are mutually exclusive. 

How does that sound?  How would you want the interface to work.. checkboxes?

Amenity:
- Shelter with Bench Underneath
- Shelter with no seating
- Bench only
- No amenity
?

**Comment by mkfreeman** [comment]
Deep appreciation for your deep dive here - we'll chat later but just dropping some notes here. 

I think the current set of variables is somewhat unusable. We created an interface for them to explore their data, but it doesn't seem super useful for them to explore them one at a time. 

Combining these 3 columns into 1 is a fabulous idea. Wheelchair boarding is orthogonal to these and can remain separate. 

The new UI could be a single bar with 5 clickable values for filtering (similar to the current "true / false" bars, but with "Bench only, no amenity, etc.". Might want to enable a ctrl + click for multi select (e.g., to get all of the shelter with + without benches). 

The stops barcharts below the table could be replace with just a has amenity / has no amenity to highlight sites needing improvement (or we may decide to build a UI to select which amenity drives the color encoding - can chat about it). 

Just making sure the following distribution makes sense to you based on your explorations thus far:

<img width="649" alt="Screenshot 2023-12-12 at 11 53 12 AM" src="https://github.com/mkfreeman/norc-map/assets/1373882/9e86eddd-fb69-421b-a639-d0c5ce392bd2">

**Comment by orcaomar** [comment]
Ok @mkfreeman  all completed in https://github.com/mkfreeman/norc-map/commit/2168101c95fc7e39f69a27a8d5f43250e6329366 and https://github.com/mkfreeman/norc-map/commit/d534900cb248bd40d4dd1ca03159780b59c28abe

The new file is in public with the name 

norcs_with_closest_stops_merged_new.geojson

Let me know if this file is missing some property, probably faster for me to just add it. 

In particular, I didn't change the name of any of the fields, just removed any extraneous fields. I didn't change names because I want the field names to align with their original data so if they look at this when I move it to a public Google Sheet (that is a good idea, will file another issue for that) then they can see the 1 to 1 correspondence in field names. 

Here is an example feature with no amenity in the cleaned data set:

`{"type": "Feature", "properties": {"Address": "2314 Islington Ave", "Age 65+ Total": 176, "All_Persons": 198, "% of Seniors": 0.8888888888888888, "latitude": 43.716308, "longitude": -79.5562717, "stop_name": "Bergamot Ave at Islington Ave", "stop_lat": 43.716772, "stop_lon": -79.556363, "wheelchair_boarding": "Some", "distance": 55, "id": 489, "source": "OpenStreetMaps", "amenity": null}, "geometry": {"type": "LineString", "coordinates": [[-79.556017, 43.716368], [-79.556169, 43.716704], [-79.556225, 43.716726], [-79.556305, 43.716752], [-79.556348, 43.716741]]}}`

here's another: 
`{"type": "Feature", "properties": {"Address": "2715 Islington Ave", "Age 65+ Total": 88, "All_Persons": 90, "% of Seniors": 0.9777777777777777, "latitude": 43.7417193, "longitude": -79.5663583, "stop_name": "Islington Ave at Kingsmoor Gate North Side", "stop_lat": 43.741105, "stop_lon": -79.56691, "wheelchair_boarding": "Some", "distance": 80, "id": 488, "source": "Google", "amenity": "Shelter With Bench Underneath"}, "geometry": {"type": "LineString", "coordinates": [[-79.56654, 43.74153], [-79.56665, 43.74151], [-79.56678, 43.74138], [-79.56682, 43.74137], [-79.5669, 43.74132], [-79.56701, 43.7413], [-79.56701, 43.7413], [-79.56694, 43.74121], [-79.5669, 43.74111]]}}`

**Comment by mkfreeman** [comment]
@orcaomar I just updated the app to use this new data structure. I opted for a bar chart to filter the type of amenity (still needs a little polish). 

If you want to change the order or contents of the columns for the table, you can do that in the dat a generation process and it will be reflected in the table (e.g., if we want amenity to appear earlier, id to appear later, etc.).

**Comment by orcaomar** [comment]
Note in all the comments above one should ignore any reference to has_bench or bench only, because as per https://github.com/mkfreeman/norc-map/issues/35 I had to redo the bench data
