### ISSUE TITLE
Link popups to google streetview

### ISSUE THREAD

**Issue by mkfreeman** [mkfreeman/norc-map#30]
Both the building and the stop

**Comment by orcaomar** [comment]
Ok I did this, but haven't pushed it to the live site.. reason being that now it seems even when I drag around a bit on the map, and don't click seemingly on anything, sometimes a street view link loads. Something about the links still being active when not visible? I'm not quite sure what is going on but I am passing this over to you because I think you'll be able to immediately understand why the links are "too active"

**Comment by mkfreeman** [comment]
I'll take a look! Might not have time till Monday, all baby pending

**Comment by mkfreeman** [comment]
Is this what you see? Liiiike, the popups being behind the map tiles? I think that you did everything correctly, I'd feel free to push to main but file this as a separate bug. 
https://github.com/mkfreeman/norc-map/assets/1373882/61b1cca6-7aba-4a85-8bb5-c176ed1dc038
